
# html lang
language: zh-cn

# main menu navigation
menu:
  # follow: /follow
  # join: /join
  Document: /doc
  home: /
  API: /api
  # service: /service
  # communication: /communication

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
  - css/reset.css
  - css/amaple.css
  - css/post.css

# scripts loaded in the end of the body
scripts:
  - lib/amaple/amaple.js