
# html lang
language: zh-cn

# main menu navigation
menu:
  # Follow: /follow
  Join: /doc/start-router
  Document: /doc/
  home: /
  API: /api
  # Service: /service
  Communication: /communication

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
  - /css/reset.css
  - /css/amaple.css
  - /css/highlight.css

# scripts loaded in the end of the body
scripts:
  - /lib/amaple/amaple.js